# Generated by Django 2.0.3 on 2018-04-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_articles',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=70)),
                ('publish_date', models.DateTimeField()),
                ('article_url', models.CharField(max_length=60)),
                ('notification', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Stockk',
        ),
    ]
