# Generated by Django 2.0.3 on 2018-04-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockWeb', '0002_auto_20180424_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_articles',
            name='publish_date',
        ),
    ]
