# Generated by Django 2.0.3 on 2018-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockWeb', '0003_remove_stock_articles_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_articles',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
