# Generated by Django 2.0.3 on 2018-04-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockweb', '0004_stock_articles_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_articles',
            name='notification',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
