# Generated by Django 2.0.3 on 2018-04-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockweb', '0005_auto_20180424_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_articles',
            name='article_url',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
