# Generated by Django 2.0.3 on 2018-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockWeb', '0006_auto_20180425_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_articles',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
