# Generated by Django 2.0.3 on 2018-05-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockweb', '0007_auto_20180425_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_data',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('publish_date', models.DateTimeField()),
                ('trading_volume', models.IntegerField()),
                ('turn_over', models.BigIntegerField()),
                ('opening_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('highest_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('change', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transaction', models.IntegerField()),
                ('last_bid_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_ask_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_earnings_ratio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
