# Generated by Django 2.0.3 on 2018-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockweb', '0008_stock_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_data',
            name='price_earnings_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
