# Generated by Django 2.0.3 on 2018-05-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockweb', '0009_auto_20180531_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock_data',
            unique_together={('code', 'publish_date')},
        ),
    ]
