# Generated by Django 2.0.3 on 2018-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockWeb', '0010_auto_20180531_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_code',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
