# Generated by Django 2.0.3 on 2018-07-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockweb', '0013_auto_20180601_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock_articles',
            new_name='StockArticles',
        ),
        migrations.RenameModel(
            old_name='Stock_code',
            new_name='StockCode',
        ),
        migrations.RenameModel(
            old_name='Stock_data',
            new_name='StockData',
        ),
    ]
